language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests" 

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed boluomo/udagram-api-feed:v2
  - docker tag udagram-api-user boluomo/udagram-api-user:v2
  - docker tag udagram-frontend boluomo/udagram-frontend:v3
  - docker tag udagram-reverseproxy boluomo/udagram-reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push boluomo/udagram-api-feed:v2
  - docker push boluomo/udagram-api-user:v2
  - docker push boluomo/udagram-frontend:v3
  - docker push boluomo/udagram-reverseproxy:v2
