version: "1"
services:
  udagram-reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy
  udagram-api-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  udagram-apifeed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
